import { Grid, Paper } from "@mui/material";
import styled from "@emotion/styled";

import {
  Competitors,
  Dividend,
  FinancialHealth,
  Fundamentals,
  MenuComponent,
  History,
  Overview,
  Ownership,
  Header,
} from "./components";

import { Fragment } from "react";
import { MenuItems } from "./components/menu";
import Head from "next/head";

export function DashboardComponent() {
  const AppComponents = getApplicationComponents();

  return (
    <Fragment>
      <Head>
        <title>Share price, News and Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        spacing={2}
        justifyContent="center"
        alignItems="flex-start"
      >
        <Grid item xs={12}>
          <Paper elevation={3}>
            <InnerContainer>
              <Header.HeaderContainer />
            </InnerContainer>
          </Paper>
        </Grid>
        <Grid item xs={2}>
          <Paper elevation={3}>
            <MenuComponent />
          </Paper>
        </Grid>
        <Grid item xs>
          {AppComponents.map((CustomComponent, index) => (
            <Fragment key={`paper_${index}`}>
              <Paper elevation={3}>
                <InnerContainer>
                  <CustomComponent
                    sectionName={MenuItems[index].replace(" ", "_")}
                  />
                </InnerContainer>
              </Paper>
              <br />
            </Fragment>
          ))}
        </Grid>
      </Grid>
    </Fragment>
  );
}

function getApplicationComponents() {
  return [
    Overview.OverviewContainer,
    Competitors.CompetitorsContainer,
    History.HistoryContainer,
    Fundamentals.FundamentalsContainer,
    FinancialHealth.FinancialHealthContainer,
    Dividend.DividendContainer,
    Ownership.OwnershipContainer,
  ];
}

// Styled Components

const InnerContainer = styled.div`
  padding: 1% 3%;
`;
