import { Grid, Paper } from "@mui/material";
import styled from "@emotion/styled";

import {
  Competitors,
  Dividend,
  FinancialHealth,
  Fundamentals,
  Menu,
  History,
  Overview,
  Ownership,
  Header,
} from "./components";

import { Fragment } from "react";
import { MenuItems } from "./components/menu";
import Head from "next/head";
import { WithVisibility } from "../../_shared_";

export function CompanyDetailsContainer() {
  return <CompanyDetailsComponent />;
}

export function CompanyDetailsComponent() {
  const AppComponents = getApplicationComponents();

  return (
    <Fragment>
      <Head>
        <title>Share price, News and Analysis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        spacing={2}
        justifyContent="center"
        alignItems="flex-start"
      >
        <Grid item xs={12}>
          <Paper elevation={3}>
            <Header.HeaderContainer />
          </Paper>
        </Grid>
        <Grid item xl={2} md={2}>
          <Paper elevation={3}>
            <Menu.MenuComponent />
          </Paper>
        </Grid>
        <Grid item xl={10} md={10}>
          {AppComponents.map((CustomComponent, index) => (
            <Fragment key={`paper_${index}`}>
              <Paper elevation={3}>
                <InnerContainer>
                  <CustomComponent
                    sectionName={MenuItems[index].replace(" ", "_")}
                  />
                </InnerContainer>
              </Paper>
              <br />
            </Fragment>
          ))}
        </Grid>
      </Grid>
    </Fragment>
  );
}

function getApplicationComponents() {
  return [
    Overview.OverviewContainer,
    Competitors.CompetitorsContainer,
    History.HistoryContainer,
    Fundamentals.FundamentalsContainer,
    FinancialHealth.FinancialHealthContainer,
    Dividend.DividendContainer,
    Ownership.OwnershipContainer,
  ].map((Component) => WithVisibility(Component));
}

// Styled Components

const InnerContainer = styled.div`
  padding: 1% 2%;
`;
